### ISSUE TITLE
Fix link to RTD Jupyter notebook

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#109]
@eteq , I applied the Astropy affiliated package template as requested in #23 and I can't get the "example notebook" to link properly in http://stginga.readthedocs.org/en/latest/stginga/ipynb.html . Could you please help, since you wrote that document? Thank you!

**Comment by pllim** [comment]
Note: I tried several variations of path names, none of which works. Looks like original path was an absolute path, so perhaps it was meant to automagically link to some kind of rendered notebook somewhere... I give up.

**Comment by pllim** [comment]
Fixing another bug reinvigorated me. Found the cause and fixed it.

**Comment by eteq** [comment]
Aha, my scheme of thinking positive vibes in your direction appears to have done the job ;)

**Comment by pllim** [comment]
Yes, very effective. Does it work at L2? :smile:

**Comment by eteq** [comment]
Well find out in a few years!

**Comment by pllim** [comment]
:+1:
