### ISSUE TITLE
Python 3k incompatibility

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/stginga#115]
## Build traceback:

```
+ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```

EDIT: Maybe it isn't an incompatibility -- I misread the traceback. Either way, it does not build under Python 3.5. Python 2.7 is OK.

**Comment by pllim** [comment]
Just need a patch like the one in astropy/package-template#180
