### ISSUE TITLE
Reset postage stamp zooms on redisplay

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/stginga#13]

**Comment by stscieisenhamer** [comment]
Hmmm zoom_fit() works except for when a new ImageViewCanvas is created. The initial viewer always has the default zoom, which appears to be '3' so there is a border.

Thoughts @ejeschke?

**Comment by ejeschke** [comment]
@stscieisenhamer, if you are creating a new `ImageViewCanvas`, simply call the method `enable_autozoom('on')` on the new viewer right after you create it.

**Comment by stscieisenhamer** [comment]
Well, worked around the whole issue by using the configure callback.
