### ISSUE TITLE
Add CITATION

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#165]
Add a CITATION file and include reference to ADASS 2018 proceedings, when that is available.

~UPDATE: Submitted to ASCL too, awaiting approval.~

**Comment by pllim** [comment]
See ejeschke/ginga#811 for ADASS 2018 citation.

**Comment by ejeschke** [comment]
Actually, it is a 2019 publication for the 2018 conference. At least according to the web entry that I found for the publisher.  I've corrected the date, and added the editors.
