### ISSUE TITLE
Update utils.scale_image to mask/ignore bad pixels

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/stginga#199]
It looks like the method `scale_image` interpolates over pixels regardless of whether they are marked as "good" or "bad" pixels in the DQ extension. It would be preferable to do the interpolation with the knowledge of such "bad" pixels and ignore/mask them out.

According to the following [link](https://jwst-pipeline.readthedocs.io/en/latest/jwst/references_general/references_general.html#data-quality-flags), the JWST pipeline marks any "bad" pixels with a 1 in bit 0 of its DQ value. So, if a pixel is flagged as "DO_NOT_USE", the downsampling should ignore it.

**Comment by ejeschke** [comment]
@pllim, pretty sure Ginga handles masked images just fine.  It might be simply a matter of making a custom loader (or adapting a plugin) to create the masked array that is stored in the `AstroImage`...

**Comment by pllim** [comment]
@ejeschke , thanks. This functionality is part of pre-processing before Ginga is used. 😄

**Comment by pllim** [comment]
@Skyhawk172 , just to be clear, other flags like `SATURATED`, `DEAD`, etc should be *included* in the interpolation?

**Comment by Skyhawk172** [comment]
My understanding is that if pixels are saturated, dead, etc, then the first bit will be set to 1 (i.e. DO_NOT_USE).  So that's really the only bit we need to look at, and we don't care _why_ they're marked as DO_NOT_USE.  @melendez: if I'm getting this wrong, please let us know.

**Comment by pllim** [comment]
[zoom algorithm](https://github.com/scipy/scipy/blob/v1.5.2/scipy/ndimage/interpolation.py#L583-L657) is not a simple mean/max/etc. If we switch to using [block_reduce](https://docs.astropy.org/en/latest/api/astropy.nddata.block_reduce.html#astropy.nddata.block_reduce), there is an option to pass in a mean/max/etc function -- do you have a preference on how you want to group the pixels together? Is `np.ma.mean` sufficient?

**Comment by Skyhawk172** [comment]
Can we pass it a spline function of order 3, similar to what scipy.interpolation.zoom does by default?

**Comment by pllim** [comment]
> Can we pass it a spline function

Yes, but that would be done before calling `block_reduce`. I am hesitant to copy-paste `zoom` algorithm as-is and drop in mask support, because that would require us to call hidden Numpy functions.

**Comment by Skyhawk172** [comment]
I was wondering if we could use `scipy.interpolate.interp2d`, which returns a function.  But for now, let's get a prototype working with `block_reduce` using the median. We'll have to play around with `block_size`.

**Comment by pllim** [comment]
I might have solved this a long time ago in [interpolate_badpix](https://stginga.readthedocs.io/en/stable/api/stginga.utils.interpolate_badpix.html). You basically want to fix the bad pixels before resampling, right? But after fixing the bad pixel, you still need to provide a function for the resampling part; median is fine by me. Thanks!

**Comment by pllim** [comment]
Cubic spline with [griddata](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) is too slow and not giving me a good result using a provided test case.

![Screenshot 2020-10-02 165452](https://user-images.githubusercontent.com/2090236/94969098-1bbcd180-04d0-11eb-9926-294dbf50f15b.jpg)

I'll have to play around with this some more.

And [interp2d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html) gives `OverflowError: Too many data points to interpolate`.

Maybe try convolution trick next...

**Comment by pllim** [comment]
Convolution is also slow (2 mins to convolve [box kernel](https://docs.astropy.org/en/latest/api/astropy.convolution.Box2DKernel.html) that is 101-pix wide with 2k by 2k image) but it works better. Also I found out that `block_reduce` isn't what we want after all and we still have to use `zoom` to downsample (so you still get your cubic spline there).

What do you think, @Skyhawk172 ? Performance might be an issue here, as the 2-min per image can add up pretty quickly to become unbearable. I thought about fixing the bad pixel after downsampling, but not sure how to downsample DQ properly; guess I'll investigate that next.

**Before and after fixing DO_NOT_USE pixels (original dimension)**

![convolution_box101](https://user-images.githubusercontent.com/2090236/94983084-8d674080-050d-11eb-9322-b75169b32510.jpg)

**Final results (new vs old)**

![convolution_vs_old_zoom](https://user-images.githubusercontent.com/2090236/94983088-8fc99a80-050d-11eb-83cf-a8fe711e4314.jpg)

**Comment by pllim** [comment]
[convolve_fft](https://docs.astropy.org/en/latest/api/astropy.convolution.convolve_fft.html) does cut down the run time per image from 2 mins to 5 secs. Still not negligible but maybe acceptable?

I also tried `Box2DKernel` and `Gaussian2DKernel` with 2 different values. Still find `Box2DKernel(101)`-ish to be prettiest for this particular image, or `Box2DKernel(99)` if you don't like 3 digits.

**Comment by Skyhawk172** [comment]
Yes, performance is important as we plan on using this feature to downsample close to 2000 individual images. 5 seconds is good, especially given that this can be done in parallel.

**Comment by pllim** [comment]
@Skyhawk172 , can you please clarify the numbers? 2000 images in a single session (i.e., single operations file)? How are you doing this in parallel?

**Comment by Skyhawk172** [comment]
Okay, that requires clarification: to downsample all these images, we've been accessing the STSGinga zoom function directly, i.e. not through QUIP. Once these images have been downsampled, then we run QUIP to mosaic them together.

**Comment by pllim** [comment]
To downsample 2000 images, at 5s a pop, that is still about 2.8 hours on single core.

**Comment by pllim** [comment]
Downsampling the DQ first and then fix is much faster (in the order of a few ms), but I don't know how robust it is yet.

![Screenshot 2020-10-05 150918](https://user-images.githubusercontent.com/2090236/95121299-de994f00-071c-11eb-8f63-89fee882518f.jpg)

**Comment by pllim** [comment]
I am not really satisfied by any of them...

![Screenshot 2020-10-06 203550](https://user-images.githubusercontent.com/2090236/95274424-c9531c00-0813-11eb-91ee-dbf352898998.jpg)

Using `photutils` as suggested in https://github.com/spacetelescope/stginga/issues/199#issuecomment-705021940 :

<img alt="Screenshot 2020-10-07 175636" src="https://user-images.githubusercontent.com/2090236/95392321-8e5df080-08c6-11eb-95a9-6342f7afb10b.jpg" width="410"/>

Some timing using 10 cores in multiprocessing for 10 images (2048 -> 500):

* Downsample only = 0.9 s
* Fix, then downsample = 9.9 s
* Fix, then downsample (with `photutils`) = 5.2 s
* Downsample, then fix = 1.9 s
* Downsample, then fix (with `photutils`) = see https://github.com/spacetelescope/stginga/pull/201#issuecomment-705839081

Multiprocessing was implemented in spacetelescope/wss_tools#72

**Comment by Skyhawk172** [comment]
It may be that we'll have to rely on applying a median filter after we've downsampled the images to really get rid of those bad pixels. We had started looking into this a while ago, got distracted, and was reminded again today. So a combination of DQ-aware downsampling plus the subtraction of a median image (built from the hundreds of images we expect) might be the solution.

**Comment by pllim** [comment]
Gotta try out this life hack from @mcara 

<hr/>

https://photutils.readthedocs.io/en/stable/api/photutils.utils.ShepardIDWInterpolator.html

When constructing, provide the coordinates of the "good" pixels (obtained, i.e., using `np.where`). Then when evaluating, give a list of "bad" pixels (also, possibly obtained using `np.where`) to evaluate the interpolator at those positions.

**Comment by mcara** [comment]
Hm... after perusing this thread, it seems that performance might be an issue with IDW interpolator. I think it is worth trying it in a notebook - it should be pretty easy to do a little demonstration. I think spline interpolation needs a regular grid which is not the case here and methods that work on non-regular grids are slow.

**Comment by mcara** [comment]
This is a *non-optimized* example of how to use IDW interpolator.
```python
import numpy as np
from astropy.io import fits
from photutils.utils import ShepardIDWInterpolator as IDW
h = fits.open('ib5t04itq_flc.fits')
d = h[1].data
m = h[3].data > 0  # indices of bad pixels
d[m] = 0  # to create an image with missing (==0) bad pixels
fits.writeto(d, 'masked.fits')
idx1 = np.where(m)
idx2 = np.where(np.logical_not(m))
idw = IDW(np.array(idx2).T, d[idx2])  # takes 3s
d[idx1] = idw(np.array(idx1).T)  # takes 3.6s - fills the holes with interpolated values
fits.writeto('interp.fits', d)
h.close()
```
<img width="1674" alt="comparison-idw" src="https://user-images.githubusercontent.com/5985250/95360175-06adbd00-0899-11eb-9e68-e9c53b8b608d.png">

You can see that this interpolation somewhat "recovers" the cosmic rays from the original image. That is because the mask did not completely mask the edge pixels of the cosmic ray creating a slightly more elevated signal around the masked regions.

**Comment by mcara** [comment]
The image above is a small fragment of a larger, 2051x4096 pixels, image. First resampling both the image and the mask should speed things up. also, having fewer "bad" pixels should help too.

**Comment by pllim** [comment]
Wow, thanks! Yeah, resampling the mask first would definitely help. I am just not sure about the fidelity.

p.s. ~Hard to tell how well it did with all the blinking.~ 😬

**Comment by mcara** [comment]
That's why I gave you the code :)

**Comment by mcara** [comment]
Try it on your specific images. It is interpolating over a "hole". If there is a complex star (=complex PSF) inside that hole - no algorithm will be able to interpolate over it with high fidelity: you are not going to see a star there. This particular image that I used is a bad example because it looks like `astrodrizzle` flagged all starts and clusters as cosmic rays.

**Comment by mcara** [comment]
Don't know how to slow down blinking in a GIF - but if you can do it in an editor - try to slow the blinking. Do you want me to remove the image?

**Comment by pllim** [comment]
@mcara, not too bad! I have added the result to https://github.com/spacetelescope/stginga/issues/199#issuecomment-704628438 .

@Skyhawk172 , can you please clarify the median image subtraction technique? Is it something to be applied within `stginga` as well? And can you please let me know what you think of all the alternatives thus far (#200 , #201 , #204 ) based on https://github.com/spacetelescope/stginga/issues/199#issuecomment-704628438 ?

Thank you, all!

**Comment by Skyhawk172** [comment]
For the median subtraction, that is entirely outside STGinga. What we have now cleans up the images quite nicely.  Let me look at the alternatives you've worked on, but it may be that a combination of a DQ-aware downsampling followed by the median filter/subtraction will do the trick.

**Comment by mcara** [comment]
@pllim With regard to https://github.com/spacetelescope/stginga/issues/199#issuecomment-704628438, I can't understand why the blob of light masked by the blue mask in the upper-left image re-appears in the interpolated image. Are you sure the downsampled mask is created correctly?

That is, could you please show the same image as in the upper-left corner (1st image") downsampled without interpolating over bad pixels `PLUS` the downsampled "blue" mask that will be used later to do the interpolation over "bad" pixels.

**Comment by pllim** [comment]
@mcara , I overlooked using `photutils` to interpolate the downsampled mask (the one shown above was using convolution). I have updated #201 to use `photutils` and posted the data you requested at https://github.com/spacetelescope/stginga/pull/201#issuecomment-705839081 . (Spoiler: Best looking one thus far for that one star!)
