### ISSUE TITLE
Move online documentation to readthedocs?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#20]
As suggested by @eteq . It is currently hosted by SSB and needs SSB group access to update.

**Comment by eteq** [comment]
FYI, I know how to do this and its pretty trivial (it takes <~5 min to set up), but it needs to be done by someone with access privileges to the repo. So if I can be added as a maintainer or something I can just do this. (Although I'm not 100% how RTD decides what you control...)

**Comment by pllim** [comment]
Ops. Didn't know you don't have the permission, sorry. Did I fix it now?

**Comment by eteq** [comment]
Nope, RTD still doesn't seem to think I have the repo... I wonder if I have to be on a team or something that's associated with the `spacetelescope` organization?

**Comment by eteq** [comment]
Oh, wait, I think it let me just do it manually: https://readthedocs.org/projects/stginga/

It's still building now, but I think maybe that was all that was needed?  We shall see...

**Comment by eteq** [comment]
Success!  See http://stginga.readthedocs.org/en/latest/

@pllim, I had to make a few changes in master, adding requirements, and you might want to check those out.  But it's working now, so I'll go ahead and close this.

**Comment by pllim** [comment]
Sorry for the inconvenience! If you still need me to tweak the permission/membership, let me know.

**Comment by pllim** [comment]
I updated the link in README to point to this new doc. Thank you, @eteq !

**Comment by eteq** [comment]
Not your fault @pllim - RTD seems to just have strange ways of deciding what repositories a user has access to...  I think we're all set now, though.

**Comment by pllim** [comment]
:+1:
