### ISSUE TITLE
Lock WCS of main viewer

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/stginga#21]
Pending discussions with ginga core itself, provide option to lock the main viewer to a particular region, not necessarily the postage stamp region.

**Comment by stscieisenhamer** [comment]
Being addressed by ejeschke/ginga#197
Once that is complete, can see what cross-plugin integration can be done there also!

**Comment by pllim** [comment]
Does Ginga's `WCSMatch` global plugin satisfy this requirement? Can we close this?

**Comment by pllim** [comment]
xref #152
