### ISSUE TITLE
Switch to astropy affiliated package template?

### ISSUE THREAD

**Issue by eteq** [spacetelescope/stginga#23]
This is not particularly critical because things are currently working fine... But we might want to consider switch to the affiliated package template for `stginga` - it makes it easier to manage a variety of things like tests/doc improvements/etc.

**Comment by pllim** [comment]
:+1: might as well

**Comment by pllim** [comment]
Just to note that Ginga also has a similar issue (ejeschke/ginga#56)

**Comment by stscieisenhamer** [comment]
:+1:

**Comment by pllim** [comment]
But given that today is the last day of the sprint and we need a working version for demo. Let's hold this off until after the demo.

**Comment by eteq** [comment]
Oh, definitely - I marked it as "low-priority" for just that reason

**Comment by pllim** [comment]
Note: http://docs.astropy.org/en/latest/development/affiliated-packages.html?packagename=stginga
