### ISSUE TITLE
Add more description of how to use a plug-in to the docs

### ISSUE THREAD

**Issue by eas342** [spacetelescope/stginga#231]
### Description

Please add an instruction for Dummies like me! I wanted to try out DQInspect as a way to view data quality information. I loaded a JWST image with:

 `stginga jw01335004001_03101_00002_nrs1_rate.fits&`

but did not see anything the Dialogs tab as described here (https://stginga.readthedocs.io/en/stable/stginga/plugins_manual/dqinspect.html). So, I thought I was doing something wrong with my installation/plugins/settings, etc.

I didn't realize that all I had to do was click on Operation --> Custom --> DQInspect
I spent a while trying different things on the command line and customization to get the plug-in to load only to realize I needed to use the `Operation` button!

**Comment by pllim** [comment]
Hello. I am glad you found this package useful and I apologize for the confusion. Would something like https://github.com/spacetelescope/stginga/pull/232 make things better for you? If not, please provide suggestions on what you expect to see. Thanks!

**Comment by eas342** [comment]
Indeed this package is very useful - DQInspect is just the tool I was looking for (and I think many other JWST users)! Thanks for adding that to the docs!
