### ISSUE TITLE
Different DQ mask colors

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#35]
@bhilbert4 can elaborate further or correct me here.
1. Mark each DQ value in different color. But where do we draw the line, as there are only so many colors you can overlay before overcrowding the display? How to handle pixels with multiple DQ flags?
2. ~~For a given DQ value, plot number of affected pixels across the ramps.~~ See #40.

**Comment by bhilbert4** [comment]
1. What is the maximum number of DQ flags that could be present? For HST I think it is 16. What if you just divide the color table up by the maximum number of possibilities and assign colors that way?  For pixels with multiple DQ values, maybe just add the RGB values of the colors for the DQ flags in question and display that pixel with the summed RGB value?
2. For a given DQ value, plot the mean signal versus time (or read number) up the ramp for all the pixels with that DQ value. I see this as a special case of a more general tool where the user can select some subset of pixels (by drawing an aperture or specifying a quadrant, etc), and the selected pixels are averaged together and a plot of signal versus time is generated from the ramp.

**Comment by pllim** [comment]
1. Depending on the colors chosen, the composite color is quickly going to be too dark to be meaningful. Some thoughts are needed. But doable.
2. I think there is already a similar tool in Ginga that can do this... Check out `LineProfile` local plugin.

**Comment by pllim** [comment]
To clarify Point 2, it sounds like what you need is to extend the functionality of `LineProfile` to enable aperture selection followed by ~~sum~~ mean, using `DQInspect` overlay to pick the location.

**Comment by pllim** [comment]
Point 2 is moved to #40.

**Comment by pllim** [comment]
@bhilbert4 , I added basic multicolor masks feature. Feel free to open a new issue if you have ideas on how to improve it.
