### ISSUE TITLE
Extend LineProfile to accept aperture

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#40]
Extend `LineProfile` local plugin (by subclassing) to also accept some kind of aperture (e.g., quadrant, circle, box, etc.). Some kind of statistics (e.g., mean) is to be performed for all pixels within the aperture for a given extension. And then the results are plotting across the ramps (i.e., time).

For the quadrant and time tags to work, JWST-specific assumptions are needed. Can probably make those configurable as well.

Originally brought up by @bhilbert4 #35.

Also see ejeschke/ginga#259.

**Comment by pllim** [comment]
This should wait till existing `LineProfile` issues are resolved first (e.g., ejeschke/ginga#188).

**Comment by pllim** [comment]
@bhilbert4 , do you have test file(s) that you can provide privately to illustrate a use case for this feature?

**Comment by bhilbert4** [comment]
Yes, we have lots of data that can be used. I'll send some to you.

**Comment by pllim** [comment]
Received two `NRC*` FITS data cube from @bhilbert4 , one is 1.3GB, and the other 2.2GB. 

If memory becomes an issue, he says, _"Maybe have the user choose which groups/integrations/x/y to load? Our largest files contain 190 groups, each of which is 2048x2048....."_

**Comment by pllim** [comment]
Got a new test file that is 393MB:
```
Filename: nrca1_47Tuc_subpix_dither1_newpos_uncal.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU     133   ()      
  1  SCI         ImageHDU        10   (2048, 2048, 10, 1)   float32   
  2  PIXELDQ     ImageHDU        10   (2048, 2048)          int32 (rescales to uint32)   
  3  GROUPDQ     ImageHDU        10   (2048, 2048, 10, 1)   uint8   
  4  ERR         ImageHDU        10   (2048, 2048, 10, 1)   float32   
  5  ZEROFRAME   ImageHDU         9   (2048, 2048, 1)       float32   
  6  ASDF        ImageHDU         7   (3495,)               uint8   
```

Some extra usage info from Bryan Hilbert below:

Currently the WCS keywords, like CRVAL, are present in extension 0, while the science data are in extension 1. That causes issues with `ds9` when you're trying to do anything with the WCS. I'm not sure where Ginga looks for these keywords. Howard tells me that at some point in the future, SSB will correct this and copy all of the WCS keywords into extension 1. **(Note to self: Setting inherit_primary_header=True in Ginga is the workaround)**

Yeah, science data extension should always be 4D....(`#integrations * #readouts per integration * y * x`) unless it is a slope image, in which case it will be 2D (just `y * x`). I'd say the science extension and maybe the ERR extension are the two where looking at values across pixels and/or up the ramp could be useful.

A readout (or "group" in JWST jargon) is the image created from a single readout of the detector. A single 2D image. With IR detectors, when they are read out, the signal in the pixels is not destroyed (i.e. sent back to zero), so you can read out multiple times to create a single "integration". So for example, if pixel A sees a source that produces 10 electrons per second, you can read out the detector at `time = [0,10,20,30]` seconds and measure `[0,100,200,300]` electrons. Those 4 readouts ("groups") then comprise an integration. Then let's say that at `time = 31` seconds, the detector is reset and all pixels go back to zero signal. Then you start over (integration # 2) and measure signal at `time = [31,41,51,61]` seconds, and again measure `[0,100,200,300]` electrons. These two integrations, which are nominally identical except for noise (or time-variable sources) are then saved in the data file in the 4D array with dimensions `(2,4,2048,2048)`. **(Note to self: Array shape (2048, 2048, 4, 2) is in IRAF format.)**

So I can see it being useful to look at signal level across groups and also integrations. For example, plotting the mean signal in some group of pixels or aperture in the groups of a single integration, and also comparing one integration to the next. Of course these are just ideas that occur to me as being potentially useful.

**EDIT: Corrected array shape note based on feedback from @philhodge . Thanks, Phil!**
