### ISSUE TITLE
BackgroundSub does not calculate background

### ISSUE THREAD

**Issue by ejeschke** [spacetelescope/stginga#44]
When I load an image and draw an annulus, the `X` and `Y` values update, but not the `Radius` or `Annulus Width` boxes.  Also, the `Background Value` box does not seem to change (not calculated).  The log does not show any errors. The `Subtract` button remains grey throughout.

This may be user error, if I am not understanding the plugin operation correctly.  I am using stginga commit 05e0777f379f7d0df1f30c5c71ffd72e5b18a854 with ginga commit 91b05b0a9e39f0fa9c3ac9f1589bc4640d91c15f.

**Comment by pllim** [comment]
#### Problem: Cannot change annulus parameters interactively

At the time when I wrote this plugin (for a different project, not `stginga`), the requirement was to have complete control over the parameter values. (Also, at that time, you had not implemented the "new way" to draw/edit shapes yet, nor the `Annulus` shape.) The fastest way to give the GUI a certain value is to enter it in the respective text box. So the workflow here is to draw an initial annulus (where you can adjust inner radius and center) on the image, and then fine-tune it by entering outer radius and width in the text boxes to update the displayed annulus.

I am also working on loading previously saved parameter values in #37, which will draw the annulus (or box) for you automatically.

I welcome any ideas to improve the user experience.

#### Problem: Cannot calculate or subtract background value

What is the format of the image? Does it have a "SCI" extension? This plugin was written with STScI data format in mind. For us, it only makes sense to calculate/subtract background in the science extension (not error or data quality arrays). This can be customized by adding the following to your `~/.ginga/general.cfg` (the whole file is in `stginga/examples/configs/` repo directory) and then changing the values according to your data format:

``` python
# Header keywords. These can be in PRIMARY header only if it is inherited.
extnamekey = 'EXTNAME'
extverkey = 'EXTVER'
sciextname = 'SCI'
errextname = 'ERR'
dqextname = 'DQ'
instrumentkey = 'INSTRUME'
targnamekey = 'TARGNAME'
```

If you have `--loglevel=10`, the log file should tell you, "Background calculation not possible for XXX extension in IMAGENAME"

**Comment by pllim** [comment]
I think I answered all the questions here. Feel free to reopen if needed, @ejeschke .
