### ISSUE TITLE
MultiImage workflow changes

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/stginga#47]
As per #32, will change the workflow as follows:
- MultiImage becomes a global plugin, and is started at any point
- To add an image, an explicit keystroke is needed.
  - Option to add automatically.
- Where the image comes from is irrelevant
- To cycle through the images, a different set of keystrokes, or overload of the arrow keys, will cycle through the JUST the images added to MultiDim, as long as that plugin has focus. Again, the cycling would cross channels if necessary.
- Make images removable.
- The image in the main viewer does not actually have to be part of the stamps. <- Need to think about that.

Steps for implementation
- [ ] Make plugin global (#96)
- [ ] Add manual addition
- [ ] Override arrow keys for cycling.
- [ ] Implement #30

**Comment by pllim** [comment]
:+1: global plugin. This automatically solves the issue of cross-channel alignment.

:-1: to keystroke. Instead, this can be drag-and-drop (more intuitive).

:-1: to keystroke override because "plugin focus" does not apply to global plugin. Instead, we can have our own "Prev" and "Next" buttons to cycle through them?

:+1: removable image. Also, an image deleted from a channel needs to be removed from this also. But what if an image is still in channel but simply fell out of `Datasrc` cache?

:+1: not forcing main viewer image to take part. I think this is a natural by-product of making auto-add optional.

**Comment by pllim** [comment]
@stscieisenhamer and @hcferguson, I am playing with the idea to completely remove `MultiImage` and `MIPick`. Instead, similar functionality can be achieved using a combination of existing plugins from Ginga itself. For example, `WCSMatch`, `Pick`, `Blink`, and multiple channels on a tiled workspace. What do you think?

**Comment by hcferguson** [comment]
@plim can you do a demo sometime?

**Comment by hcferguson** [comment]
@plim can you do a demo sometime?

**Comment by hcferguson** [comment]
@plim can you do a demo sometime?

**Comment by hcferguson** [comment]
@plim can you do a demo sometime?

**Comment by hcferguson** [comment]
@pllim can you do a demo sometime?

EDIT: Removed duplicate comments. Corrected username.

**Comment by pllim** [comment]
If we have another visualization sprint scheduled, this can be part of that sprint.

**Comment by pllim** [comment]
@hcferguson , with the latest dev Ginga (as of Jan 27, 2017), I believe the following workflow using core Ginga, without the special `MultiImage` and `MIPick` plugins here, effectively supersedes those 2 plugins, which I am in favor to get rid of (which will also conveniently close a bunch of open issues):

1. Open the images of interest from command line, each image in its own channel using `ginga --sep s*_sci.fits` command. Also see ejeschke/ginga#428.
2. Change the "Workspace" drop-down menu option to "Grid".
3. Start `WCSMatch` global plugin and set "Reference Channel" to "Image" (or whichever channel you want to use as primary).
4. Start `Pick` local plugin in the primary channel.
5. Zoom and pick your object of interest.

Screenshot of the result is attached. In this screenshot, every channel is using its own auto-levels for scaling. You can manipulate Ginga configuration to have them all on the same scale, but that option is not pretty for this particular example:

![screenshot-ginga image](https://cloud.githubusercontent.com/assets/2090236/22381936/9ae355c8-e491-11e6-91d4-b1b65c1f9a57.png)

What do you think?

**Comment by pllim** [comment]
xref #152.
