### ISSUE TITLE
cannot interact with box: always panning

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/stginga#48]
In MultiImage, MIPick, or Pick, the box cannot be interacted with. The main image is always in pan mode. The one way I have found is to hit the 'd' key. This should bring up the distribution algorithm choosing, but instead allows moving and editing of the box.

It doesn't matter what mode is chosen: move, draw, or edit.

Notes
- With latest master of ginga (23Nov2015)
- OS X with trackpad

**Comment by stscieisenhamer** [comment]
@ejeschke Heads up. However, I have just upgraded to OS X 10.10, and am looking to see if some default with the trackpad has changed.

**Comment by stscieisenhamer** [comment]
OK, this makes absolutely no sense: So, I had run our stginga script a number of times, always with the above issue.

Then, just for kicks, I ran ginga expecting the same result. But, to much amazement, it operated normally; I was not perpetually stuck in pan mode. This is baffling because stginga is just a wrapper around ginga.

Well, then I run stginga. Lo and behold, all now works normally!?!?!?!

WAT

**Comment by ejeschke** [comment]
@stscieisenhamer, can you try a couple of things?  1) try pressing `Command` with the cursor explicitly focused in the window (if you are using a Mac, `Control` otherwise) when it appears stuck in Pan mode?  Also 2) try the `Escape` key.  Let me know your findings.

**Comment by ejeschke** [comment]
I've noticed that sometimes on Linux, if you press `Control` in the window, but then navigate _away_ from the window before releasing, Ginga does not get the event notification of `Control` key going up.  I've never seen this on  a Mac, but it may be possible.

**Comment by stscieisenhamer** [comment]
@ejeschke I had tried `Escape` and other modifier/key/click combos, all to no avail.

I suspect, due to the events of stginga not working->ginga working->stginga working, that somehow there was another cached pyc issue.

If it occurs again, I'll at least be prepared to track down.
