### ISSUE TITLE
"Correct WCS" function in `Pick`

### ISSUE THREAD

**Issue by ejeschke** [spacetelescope/stginga#54]
It looks like there is a half finished "Correct WCS" function in `Pick`.  Is this something that started in `MPick`?

**Comment by stscieisenhamer** [comment]
If that is in the official ginga code, no, not started by me anyways. I remember seeing that and was going to ask about it. However, for `MIPick`, the only intended change was to use the common Region object between that and MultiImage.

**Comment by ejeschke** [comment]
Interesting.  I have no memory of starting that, and the approach does not look like mine. I'll dig some more, but probably I will excise this bit from `Pick`.
