### ISSUE TITLE
Document usage with IPython Notebook

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#56]
Populate `docs/source/ipynb.rst` with contents of the Sprint demo after #55 is merged.

**Comment by pllim** [comment]
c/c @sosey , since I think she mentioned she already has some examples?

**Comment by sosey** [comment]
examples of writing docs in notebook? I've written tutorials, what exactly do you mean?

**Comment by pllim** [comment]
Something about using Ginga in the notebook environment.

**Comment by stscieisenhamer** [comment]
I believe this was to document what @eteq had done, whom he said was going to look at it before end-of-week.

**Comment by pllim** [comment]
No rush. I got a big PR coming (#61).
