### ISSUE TITLE
DQInspect: Handle WFPC2 file format

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#6]
Continued from related discussions in ejeschke/ginga#162. c/c @mcara

**Comment by pllim** [comment]
@mcara 

> WFPC2 (and other instruments) have DQ flags in a separate file (e.g., "_c1m.fits")

Ah, yes. Currently, you can still use the DQ plugin to inspect `c1m` files, but only if you set the following in your `~/.ginga/general.cfg`:

``` python
dqextname = 'SCI'
```

The need to do so means that you cannot simultaneously inspect, say, ACS images. I have no idea why the Archive would set a WFPC2 data quality file to have `EXTNAME=SCI` and not `EXTNAME=DQ`.

Alternately, you can manually change the `c1m` files to have `EXTNAME=DQ`. Then you can use the default setting below that works on other instruments:

``` python
dqextname = 'DQ'
```

If you want to inspect WFPC2 DQ on its science data, i.e., overlay `c1m` information on `c0m` image display, it is not possible right now. In fact, the plugin behaves weirdly when it does not find `DQ` extension in the same image. So, one way to accomplish this is to subclass this plugin and write a custom version just for WFPC2 data structure.

However, given that we do not have funding for WFPC2 work, it is not high on the priority list to implement.

**Comment by pllim** [comment]
@mcara , I added WFPC2 support in #9. With this fix, you should not have to manually change `c1m` extension name to `DQ` anymore. And the plugin should also work when both WFPC2 and non-WFPC2 data are loaded in the same viewer.

The WFPC2 implementation is a bit hacky, given the number of assumptions that went into it. But given that WFPC2 archive is now static, this solution should not need changing in the future.

**Comment by mcara** [comment]
> I have no idea why the Archive would set a WFPC2 data quality file to have EXTNAME=SCI and not EXTNAME=DQ

I have noticed the same thing when working on skymatch. However, not all WFPC2 DQ files have extension 'SCI': some did have 'DQ' (I think). Probably something went wrong with one of the releases and it did not get noticed until too late.

**Comment by pllim** [comment]
Huh. That's "fun". I'll reopen this until I can address the inconsistent EXTNAME problem.

**Comment by pllim** [comment]
Fixed (again) in #24.
