### ISSUE TITLE
MIPick should subclass Pick

### ISSUE THREAD

**Issue by ejeschke** [spacetelescope/stginga#63]
Right now `MIPick` is a copy of `Pick` with some minor changes.  I would suggest subclassing `Pick` instead.  I noticed while testing `MIPick` the other day that it is already missing some of the enhancements and updates to `Pick`, like the radial plot curve fit.

We subclass a lot of the standard plugins here at Subaru in order to customize them for our specific observation workflow.  It works pretty well.  Occasionally we need to modify the "core" plugin to add a callback or to expose a structure so that it can enable some functionality in the subclass. Generally this can be done in a pretty non-invasive way.  Very occasionally the subclass has such radical changes that it becomes better to disentangle them by copying the relevant parts of the core plugin and skipping the subclassing, but I would say that in the current form `MIPick` isn't fundamentally different.

**Comment by stscieisenhamer** [comment]
Agreed. It was originally meant just as a demonstration. However, it seems to actually be useful and will make it proper.

**Comment by pllim** [comment]
QUIP is offically using `stginga` now, so I think it is time we address some of the issues here. I'll start by taking a stab at this. FYI.

**Comment by pllim** [comment]
Note to self: To know whether code was added by subclass or from parent, see `Pick` at https://github.com/ejeschke/ginga/blob/ee95d776bd4f9ec97e1cec312d8e842c95e41ee0/ginga/misc/plugins/Pick.py and the latest

**Comment by pllim** [comment]
Deleted over 1000 lines! :smile:
