### ISSUE TITLE
RTD build failed

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#71]
@eteq , RTD build has been failing since the past week. The latest log (https://readthedocs.org/projects/stginga/builds/3596379/) suggests it might have something to do with your IPython notebook documentation. Could you please look into this? Thank you!

**Comment by pllim** [comment]
Need to check https://readthedocs.org/projects/stginga/builds/3659768/ before closing.

**Comment by pllim** [comment]
Fixed!

**Comment by eteq** [comment]
@pllim for some reason I didn't see the notifications about this until now... But good that it's fixed! ;)

**Comment by pllim** [comment]
No problem, @eteq .
