### ISSUE TITLE
Custom layout might not be consistent if user does not use stginga command

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#78]
In `gingawrapper.py`, `gmain.default_layout` is re-defined to accommodate `MultiImage` plugin. I believe this only works if user starts Ginga use `stginga` command directly. What if user uses our plugins in the two other ways that we said they could (see http://stginga.readthedocs.org/en/latest/run.html)?

**Comment by stscieisenhamer** [comment]
Will have to explore that. i would presume they end up in the "standard" areas, which, if it worked as before, would be OK. But will require testing and modification.

Is there a ginga standard for this situation?

**Comment by pllim** [comment]
@stscieisenhamer , I think our situation is pretty "special", so I am not aware of a standard solution. But maybe @ejeschke can correct me if I am wrong.

**Comment by ejeschke** [comment]
From what I understand, it will work provided the user also sets the layout to have compatible workspace names (and dimensions, obviously) for all the stginga plugins that don't use the same ones as the reference viewer.
