### ISSUE TITLE
Have MIPick coexists with Pick

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#97]
I think as a side effect of #63, if I have both `Pick` (parent class) and `MIPick` (subclass) up at the same time, one of them does not work. Need to sort this out. But not critical because no one would try this, right, right?

**Comment by ejeschke** [comment]
I think they should work.  The `MPick` instance should have its own copy of everything.  They would be sharing some of the same names for tags, but those should be on different canvases, so no problem.

Can you explain how it does not work?  Is there an error message?

**Comment by pllim** [comment]
I think it's because I use the same layer tag. I'll see if renaming the layer tag in subclass would work. I don't think the fix will be complicated.

**Comment by ejeschke** [comment]
Yeah, that sounds right.
